### PR TITLE
Update v4-analytics-to-aep-analytics.md

### PR DESCRIPTION
**Pull request by stcheng-adobe**
@calebk1 Nice catch, can you approve and merge the change.

### CODE REVIEW

**Comment by stcheng-adobe** [comment]
Actually, I noticed that we also have Experience Platform and AEP mentioned before number 3.  @calebk1 Any suggestions?

**Comment by calebk1** [comment]
@stcheng-adobe If we have mentions of Adobe Experience Platform earlier, we can keep the ones that are just "Experience Platform" as is. However, we do need to change the ones that say "AEP" to either "Experience Platform" or "Platform".

**Comment by emdobrin** [comment]
@stcheng-adobe can you please update based on https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/pull/593#issuecomment-874228842

**Comment by emdobrin** [comment]
Closing this for now.

**Pull request closed without merging**
